#########################################
# generate pngs of a UMAP in a for-loop #
#########################################

library(Seurat)
library(tidyverse) # loads ggplot2

# let's load in an object (file generated by mk_data1.R)
input.dir <-"~/Projects/10_Batchcor/output"
data <- readRDS(file.path(input.dir,"cbmc.rds"))

# let's generate a couple of differen clusterings in a for loop
# each cluster will be written as follows: data$RNA_snn_res.0.7
# 

res <- c(0.7,0.8,0.9,1)

for (i in res) {
  # check where we are 
  print(i)
  
  # run the clustering
  data <- FindClusters(data, resolution = i)
  
  # create the ggplot object
  umap.data <- DimPlot(data, label = TRUE) + NoLegend()
  
  # write it out as a png
  # first create the filename in the loop
  filename <- paste0("cbmc_umap_res",i)
  png(file=file.path(input.dir,filename),
      width=700, height=700)
  print(umap.data)
  dev.off()
  
}
